### ISSUE TITLE
Sending assets with path payments

### ISSUE THREAD

**Issue by dchrist22** [QuantozTechnology/Centaurus#2]
In **controlers.send.js**:

When using path payments, additional informations are needed for the transaction. 
There are two different Assets involved: `sendAsset` and `destAsset`. 
Two amounts: `destAmount` (the amount the destination accounts gets in destAsset) and `sendMax` the (maximum amount the sender wants to pay in sendAsset).
And also 'path' (array of Assets which are involved in the path).

So I made a [sketch](https://github.com/QuantozTechnology/Centaurus/files/79682/path_payments.pdf), how the send screen would look like, if all these values have to be added manually by the user. That way the app would show additional fields, if an asset other than XLM is chosen and would then use the path payment operation. If XLM is chosen the normal screen would be seen and the payment operation would be used. `path` should be available with `context.alternatives`.

Otherwise there is maybe a way to get the additional values without the need of a user input, to change the send screen as little as possible. But i think at least the two assets are needed to get filled in manually.

**Comment by raymens** [comment]
Either one of the following two information sets are required:
`[ from, to, sourceAsset, sourceAmount, destAsset ]` 
or 
`[ from, to, sourceAsset, destAsset, destAmount ]`

So either `destAmount` or `sourceAmount` must be calculated using the paths. The user just needs to fill in 1 of them.

**Comment by dchrist22** [comment]
So in that case I think it would make more sense to use the `destAmount` set.

**Comment by raymens** [comment]
No, use both of them. If the user enters a dest_amount, calculate source_amount and the other way around.

**Comment by mvaneijk** [comment]
And the amounts should be filled in so that the user can check the amounts before hitting send

**Comment by mvaneijk** [comment]
fixed by #2
